<h2>What is Numpy</h2>
<span>
NumPy is a popular Python library used for numerical computations. It provides support for large multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.<span>

In [1]:
import numpy as np

<h2>Basic Numpy Arrays</h2>

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [7]:
array_a = np.array([5,6,7,8])
array_b = np.array([10,11,12,13,14])
array_c = np.array([3.3,4.4,3.56])

In [8]:
#To disclose what array_a and array_b contains
print("This is array a",array_a)
print("This is array b",array_b)

This is array a [5 6 7 8]
This is array b [10 11 12 13 14]


In [10]:
array_c.dtype, array_b.dtype

(dtype('float64'), dtype('int32'))

In [12]:
array_b.dtype == array_a.dtype

True

## Multi dimesional Arrays

In [18]:
array_new = np.array(([3,4,5],[6,7,8]))
array_new.shape

(2, 3)

In [19]:
array_new.size

6

In [21]:
array_1 = np.array((
                    [1,2,3],
                    [3,4,5],
                    [6,7,8]

                    ))
array_1[0:2]

array([[1, 2, 3],
       [3, 4, 5]])

In [24]:
array_1[:2,:3]

array([[1, 2, 3],
       [3, 4, 5]])

In [26]:
array_1.sum()

39

In [27]:
array_1.mean()

4.333333333333333

In [29]:
array_1.var()#Variance of the matrices

4.888888888888889

In [30]:
array_1.std()  #Standard-deviation of the matrices

2.211083193570267

<h2 style = "color:white background-color:red">  VECTOROIZATION AND BROADCASTING OPERATIONS</h2>

In [31]:
a = np.arange(4)

In [32]:
print(a)

[0 1 2 3]


In [33]:
a+10

array([10, 11, 12, 13])

In [34]:
np.random.random(size=2)

array([0.30715193, 0.52705218])

In [35]:
np.random.normal(size= 4)

array([ 1.670787  ,  1.21012796, -0.23387351,  2.62196371])

<h4> Numpy Universal Function</h4>

In [38]:
np.max(a), np.min(a),np.exp(a)

(3, 0, array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692]))

## PANDAS

In [39]:
import pandas as pd

In [40]:
data = pd.Series([35,66,22,45,211,100])
data

0     35
1     66
2     22
3     45
4    211
5    100
dtype: int64

In [43]:
data.name = "Tutorial Starts"
data

0     35
1     66
2     22
3     45
4    211
5    100
Name: Tutorial Starts, dtype: int64

In [44]:
data.index = ["A","B","C","D","E","F"]

In [45]:
data

A     35
B     66
C     22
D     45
E    211
F    100
Name: Tutorial Starts, dtype: int64